baseURL = 'https://fxl.netlify.app/'
languageCode = 'en-us'
title = 'Fang Xi Lin'
theme = 'split'
disableKinds = ["section", "taxonomy", "term", "RSS", "sitemap"]

# Local preview mode
relativeURLs = true
uglyURLs = false

# Enter your tracking code to enable Google Analytics
# googleAnalytics = ""

# Copyright
copyright = "&copy;2023 Fang Xi Lin"

[params]

  # Metadata for search engines and social sharing
  author = "Fang Xi Lin"
  description = "Fang Xi is a data scientist and swing dancer based in Toronto, Canada."
  #shareImage = "images/social.jpg"
  #twitterHandle = "onepagelove"

  # Favicon
  favicon = "favicon.ico"

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "images/background.jpg"
      position = "center center"

    # Video
    [params.visual.video]
      enable = false
      mute = true
      file = "videos/background.mp4"
      # youtubeId = "dk9uNWPP7EA"

  # Links
  #
  # Links List #1
  [[params.links]]
    [params.links.list1]
      heading = "Data Science"

      [[params.links.list1.link]]
        text = "Resumé / CV"
        url = "files/FangXi-Lin-data-scientist.pdf"
        new_tab = true # new tab

      [[params.links.list1.link]]
        text = "Projects"
        url = "projects"

    #   [[params.links.list1.link]]
    #     text = "Contact Me"
    #     url = "contact-me"
    #     new_tab = false # Default, open at same tab

  # Links List #2
  [[params.links]]
    [params.links.list2]
      heading = "Dance"

      [[params.links.list2.link]]
        text = "Private lesson"
        url = "private-lesson"

      [[params.links.list2.link]]
        text = "Teaching"
        url = "teaching"

    #   [[params.links.list2.link]]
    #     text = "Projects"
    #     url = "https://instagram.com/quantum.fx"

  # Links List #3
  [[params.links]]
    [params.links.list3]
      heading = "Contact"

      [[params.links.list3.link]]
        text = "LinkedIn"
        url = "https://www.linkedin.com/in/fangxilin"
        new_tab = false # Default, open at same tab

    #   [[params.links.list3.link]]
    #     text = "GitHub"
    #     url = "https://github.com/quantumfx/"
    #     new_tab = false # Default, open at same tab

      [[params.links.list3.link]]
        text = "Instagram"
        url = "https://instagram.com/quantum.fx"
        new_tab = false # Default, open at same tab

      [[params.links.list3.link]]
        text = "Email"
        url = "mailto:contact@fangxilin.com"
        new_tab = false # Default, open at same tab

  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split
